# Site Settings
title: Pixel to EM
app-name: "Pixel to EM"
description: ""
author: "https://twitter.com/fcschimidt"
baseurl: ""
url: "https://pixel.fcschmidt.me"

# Build settings
highlighter: rouge
markdown: kramdown

# Google Analytics
google__analytics:
  tracking-id: 

gems:
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
