# Site Settings
title: Pixel to EM
description: ""
author: "https://twitter.com/fschimidt"
baseurl: ""
url: "http://fcschmidt.me/pixel-to-em"

# Build settings
highlighter: rouge
markdown: kramdown

# Google Analytics
google__analytics:
  tracking-id: 

gems:
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore